
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mikearaya"
    commit-message:
      prefix: "[npm] "
    labels:
      - "npm"
      - "dependencies"
    reviewers:
      - "mikearaya"
    target-branch: "main"
    open-pull-requests-limit: 10
      
